project:
  type: website
  output-dir: docs

website:
  title: "Sven Panis"
  description: "Personal website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - publications.qmd
      - EHAexamples.qmd

format:
  html:
    theme: sandstone
    mainfont: courier
    fontsize: 1.5rem
    monofont: courier new
    css: styles.css
    toc: true
    toc-location: right



