project:
  type: website
  output-dir: docs

website:
  title: "Sven Panis"
  description: "Personal website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
    toc-location: right



