---
title: "projects"
format: html
---

## Bayesian Event History Analysis

What is the most informative and less biased way to analyze response times, saccade latencies, and fixation durations? Which approach can deal with right-censored observations (e.g., trials without a response)? Dr. Richard Ramsey and I developed a set of tutorials for applying Bayesian event history analysis to response time (RT) data, and Bayesian micro-level speed-accuracy tradeoff analysis to timed accuracy data. The tutorials are written in R and can be downloaded [here](https://github.com/sven-panis/Tutorial_Event_History_Analysis). A PsyArXiv preprint on the tutorials is available [here](https://osf.io/preprints/psyarxiv/57bh6_v3).


## Revisiting the Speed-of-Processing Hypothesis

When is conflict detected by the brain? What is the temporal dynamics of conflict detection versus resolution? We apply event history analysis and micro-level speed-accuracy tradeoff analysis to the RT + accuracy data measurend in various manual interference tasks (Stroop, Simon, flanker, stop-signal) that employ a stimulus-onset-asynchrony manipulation, to study whether the onset of interference in the hazard functions of response occurrence is time-locked to the visual onset of the task-irrelevant feature. For example, does word meaning in the Stroop task causes conflict starting around 450 ms after the letters appear? Does spatial location in the Simon task causes conflict starting around 150 ms after the location is stimulated?

## Stroop effects in RT distributions and pupillometry

How do Stroop effects in RT distributions versus pupil size time series compare? Can we identify all three conflict components (task, semantic, response conflict) in both dependent measures? Is there a constant subject-specific time lag between the onset of a Stroop conflict component in RT data and in pupil size data? Does the pre-stimulus pupil size affect the shape of the RT distributions?




