---
title: "publications"
format: html
---

## Clinical experimental psychology

Burnett, H. G., Panis, S., Wagemans, J., & Jellema, T. (2015). Impaired identification of impoverished animate but not inanimate objects in adults with high-functioning autism spectrum disorder. Autism Research, 8(1), 52-60.

Evers, K., Panis, S., Torfs, K., Steyaert, J., Noens, I., & Wagemans, J. (2014). Distributed interplay between mid- and high-level vision in ASD? Evidence from a contour identification task with everyday objects. Journal of Autism and Developmental Disorders, 44, 801-815.

Panis, S., Torfs, K., Gillebert, C. R., Wagemans, J., & Humphreys, G. W. (2017). Neuropsychological evidence for the temporal dynamics of category-specific naming. Visual Cognition, 25(1-3), 79-99.

## Experimental psychology

Panis, S. (2020). How can we learn what attention is? Response gating via multiple direct routes kept in check by inhibitory control processes. Open Psychology, 2, 238-279. https://doi.org/10.1515/psych-2020-0107

Panis, S., De Winter, J., Vandekerckhove, J., & Wagemans, J. (2008). Identification of everyday objects on the basis of fragmented versions of outlines. Perception, 37 (2), 271-289.

Panis, S., & Hermens, F. (2014). The time course of spatial contextual interference: Event history analyses of simultaneous masking by nonoverlapping patterns. Journal of Experimental Psychology: Human Perception and Performance, 40(1), 129-144.
doi: 10.1037/a0032949

Panis, S., Moran, R., Wolkersdorfer, M. P., & Schmidt, T. (2020). Studying the dynamics of visual search behavior using RT hazard and micro-level speed-accuracy tradeoff functions: A role for recurrent object recognition and cognitive control processes. Attention, Perception, & Psychophysics, 82, 689-714. https://doi.org/10.3758/s13414-019-01897-z

Panis, S., & Ramsey, R. (July, 2025). Event History Analysis for psychological time-to-event data: A tutorial in R with examples in Bayesian and frequentist workflows. PsyArXiv Preprint, https://osf.io/preprints/psyarxiv/57bh6_v2

Panis, S., & Schmidt, T. (2016). What is shaping RT and accuracy distributions? Active and selective response inhibition causes the negative compatibility effect. Journal of Cognitive Neuroscience, 28(11), 1651-1671. doi: 10.1162/jocn_a_00998

Panis, S., & Schmidt, T. (2020, May 25). What is causing “inhibition of return” in spatial cueing tasks? Temporally disentangling multiple cue-triggered effects on multiple time scales using response history and conditional accuracy analyses.
https://doi.org/10.31234/osf.io/udpvs

Panis, S., & Schmidt, T. (2022). When does “inhibition of return” occur in spatial cueing tasks? Temporally disentangling multiple cue-triggered effects using response history and conditional accuracy analyses. Open Psychology, 4, 84-114. https://doi.org/10.1515/psych-2022-0005

Panis, S., Schmidt, F., Wolkersdorfer, M. P., & Schmidt, T. (2020). Analyzing response times and other types of time-to-event data using event history analysis: A tool for mental chronometry and cognitive psychophysiology. i-Perception. November 2020. doi:10.1177/2041669520978673

Panis, S., Vangeneugden, J., & Wagemans, J. (2008). Similarity, typicality, and category-level matching of morphed outlines of everyday objects. Perception, 37 (12), 1822-1849.

Panis, S., & Wagemans, J. (2009). Time-course contingencies in perceptual organization and identification of fragmented object outlines. Journal of Experimental Psychology: Human Perception and Performance, 35 (3), 661-687.

Sassi, M., Vancleef, K., Machilsen, B., Panis, S., & Wagemans, J. (2010). Identification of everyday objects on the basis of Gaborized outline versions. i-Perception, 1(3), 121-142.

Schmidt, T., Panis, S., Wolkersdorfer, M. P., & Vorberg, D. (2022). Response inhibition in the negative compatibility effect in the absence of inhibitory stimulus features. Open Psychology, 4(1), 219-230.

Torfs, K., Panis, S., & Wagemans, J. (2010). Identification of fragmented object outlines: A dynamic interplay between different component processes. Visual Cognition, 18(8), 1133-1164.

Vandekerckhove, J., Panis, S., & Wagemans, J. (2007). The concavity effect is a compound of local and global effects. Perception & Psychophysics, 69(7), 1253-1260.

Wolkersdorfer, M. P., Panis, S., & Schmidt, T. (2020). Temporal dynamics of sequential motor activation in a dual-prime paradigm: Insights from conditional accuracy and hazard functions. Attention, Perception, & Psychophysics, 82, 2581-2602. https://doi.org/10.3758/s13414-020-02010-5

## fMRI

Gillebert, C. R., Op de Beeck, H., Panis, S., & Wagemans, J. (2009). Subordinate categorization enhances the neural selectivity in human object-selective cortex for fine shape differences. Journal of cognitive Neuroscience, 21, 1054-1064.

Panis, S., Vangeneugden, J., Op de Beeck, H., & Wagemans, J. (2008). The representation of subordinate shape similarity in human occipitotemporal cortex. Journal of Vision, 8(10), 1-15.

Panis, S., Wagemans, J., & Op de Beeck, H. (2011). Dynamic norm-based encoding for unfamiliar shapes in human visual cortex. Journal of Cognitive Neuroscience, 23(7), 1829-1843. https://doi.org/10.1162/jocn.2010.21559

## Eye-tracking

Germeys, F., De Graef, P., Panis, S., Van Eccelpoel, C., & Verfaillie, K. (2004). Transsaccadic integration of bystander locations. Visual Cognition, 11(2-3), 203-234.

## Human factors

Muramalla, S., Tarawneh, R. A., Humayoun, S. R., Moses, R., Panis, S., & Ebert, A. (2017). Radial vs. rectangular: Evaluating visualization layout impact on user task performance of hierarchical data. IADIS International Journal on Computer Science & Information Systems, 12(2), 17-31.
